<!-- <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN"> -->
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
	<script language="JavaScript">
		document.write('<script language="JavaScript" src="javascript/datax.js"></sc' + 'ript>');
	</script>
	<meta name="MSSmartTagsPreventParsing" content="true">
	<link rel="stylesheet" type="text/css" href="<?php print($sess_style); ?>">
	<link rel="stylesheet" type="text/css" href="css/tests.css">
	<link rel="stylesheet" type="text/css" href="css/menuh.css">

<!--[if IE]>
	<link rel="stylesheet" type="text/css" href="css/ie.css">

<![endif]-->



    <title><?php print($PHP_SELF); ?></title>
    <base target="_self">
</head>
<?php
//require_once('dbfunctions.php');
//require_once('fdataentry.php');
print('<body>');
print('<table width="100%" cellpadding="0" cellspacing="0" >'."\n");
print('<tr><td id="pageBody" >');

?>


