SET FOREIGN_KEY_CHECKS=0;
set SQL_MODE="";
DROP VIEW IF EXISTS languages;
CREATE VIEW languages AS
    SELECT *
    FROM sys_languages;



DROP TRIGGER IF EXISTS `on_delete_projects`;
DELIMITER //
CREATE TRIGGER `on_delete_projects` AFTER DELETE ON `arc_pratiche_prj`
FOR EACH ROW BEGIN
    UPDATE pratiche
    SET project_id = NULL
    WHERE project_id = old.project_id;
END
//
DELIMITER ;

ALTER TABLE `pratiche` CHANGE `DATASTMP` `DATASTMP` DATE NULL DEFAULT NULL;

ALTER TABLE `pratiche`
    CHANGE `PRATICA_ID` `PRATICA_ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT;
# ALTER TABLE `pratiche` DROP `PRATICA_USCITA_ID`;
ALTER TABLE pratiche ADD COLUMN MAIL_SENT_ID varchar(255) DEFAULT NULL;
ALTER TABLE pratiche ADD COLUMN ANNULLATO enum('SI','NO') NOT NULL DEFAULT 'NO';
ALTER TABLE pratiche ADD INDEX MAIL_SENT_ID (MAIL_SENT_ID);

ALTER TABLE `arc_pratiche_prj` CHANGE `PRATICA_ID` `PRATICA_ID` INT(11) UNSIGNED NOT NULL;


ALTER TABLE `arc_pratiche_prj`
    ADD FOREIGN KEY (`PRATICA_ID`) REFERENCES `pratiche` (`PRATICA_ID`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT;

SET FOREIGN_KEY_CHECKS=0;