

ALTER TABLE `arc_sospensioni` CHANGE `PROTOENTRATA` `PROTOENTRATA` INT( 11 )  NULL DEFAULT NULL ,
CHANGE `PROTOUSCITA` `PROTOUSCITA` INT( 11 ) NULL DEFAULT NULL ;

/* verificare indici */
ALTER TABLE `arc_sospensioni` ADD INDEX ( `PROTOENTRATA` ) ;
ALTER TABLE `arc_sospensioni` ADD INDEX ( `PROTOUSCITA` ) ;
ALTER TABLE `sys_responsabilities` CHANGE `CREATION` `CREATION` DATETIME NULL DEFAULT null, CHANGE `UPDATED` `UPDATED` DATETIME NULL DEFAULT null;
ALTER TABLE `sys_pages_functions` CHANGE `CREATION` `CREATION` DATETIME NULL DEFAULT null, CHANGE `UPDATED` `UPDATED` DATETIME NULL DEFAULT null;

