ALTER TABLE `uploads` ADD `AMBITO` VARCHAR(120) NULL AFTER `PUBBLICATO_MIBACT`, ADD `SETTORE` VARCHAR(120) NULL AFTER `AMBITO`, 
ADD `NATURA_ATTO` VARCHAR(120) NULL AFTER `SETTORE`, ADD `A_B` VARCHAR(120) NULL AFTER `NATURA_ATTO`, ADD `TIPO_PROCEDIMENTO` VARCHAR(120) NULL AFTER `A_B`;
